pipeline {
  agent any //Es Una instancia de jenkis
  tools {
    nodejs 'node-11.1.0' 
  }
// Cuanto tiempo debe correr nuestro job
  options {
    timeout(time: 2, unit: 'MINUTES')
  }
// Son los pasos donde va ejecutar mi codigo
  stages {
    stage('Install dependencies') {
      steps {
        // sh 'cd jenkins-tests && npm i'
         bat 'cd jenkins-tests && npm i'
      }
    }
    stage('Run tests') {
      steps {
        // sh 'cd jenkins-tests && npm t'
        bat 'cd jenkins-tests && npm t'
      }
    }
  }
}
