pipeline {
  agent any // Esto indica que el pipeline puede ejecutarse en cualquier agente disponible en Jenkins

  // Configuración de las herramientas utilizadas en el pipeline
  tools {
    // Aquí debes usar la versión correcta de Node.js que esté configurada en Jenkins
    nodejs '21.7.1' // Esta es la versión que estás utilizando, asegúrate de que esté configurada en Jenkins
  }

  // Configuración de las opciones del pipeline
  options {
    timeout(time: 2, unit: 'MINUTES') // Establece un tiempo máximo de ejecución para el job
  }

  // Definición de las etapas del pipeline
  stages {
    stage('Install dependencies') {
      steps {
        // Usa 'bat' en lugar de 'sh' para ejecutar comandos en sistemas Windows
        bat 'cd jenkins-tests && npm i' // Instala las dependencias del proyecto
      }
    }
    stage('Run tests') {
      steps {
        bat 'cd jenkins-tests && npm t' // Ejecuta las pruebas del proyecto
      }
    }
  }
}
